#!/usr/bin/env python3
"""
release_validator.py - Release safety gates for generated blocklist artifacts.

This module consumes the operational reports generated by the downloader and
pipeline, scans the final output artifact, checks release canaries, and compares
against an optional previous release output.
"""

import argparse
import json
import math
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final

from scripts import __version__
from scripts.cleaner import has_unsupported_modifiers
from scripts.compiler import (
    LOCAL_HOSTNAMES,
    PLAIN_DOMAIN_PATTERN,
    extract_abp_info,
    extract_hosts_info,
    walk_parent_domains,
)
from scripts.release_evidence import (
    COVERAGE_EFFECT_BLOCK,
    RELEASE_EVIDENCE_SCHEMA_VERSION,
    SCOPE_APEX,
    SCOPE_APEX_AND_SUBDOMAINS,
    SCOPE_EXACT_HOST,
    SCOPE_SUBDOMAIN,
    SCOPE_UNSCOPED_GLOBAL,
    SCOPE_WILDCARD_APEX_ALLOWED,
    SCOPE_WILDCARD_CHILD,
    CoverageRecord,
    compact_source_health_context,
    compare_membership,
    coverage_records_from_rules,
    fingerprint_membership,
    membership_churn_to_dict,
    record_covers_canary_scope,
    render_diagnostic_sidecar,
    write_report_json,
)
from scripts.rule_syntax import classify_rule_syntax

# =============================================================================
# CONFIGURATION CONSTANTS
# =============================================================================

VALIDATION_SUMMARY_SCHEMA_VERSION: Final[int] = 1
SOURCE_HEALTH_SCHEMA_VERSION: Final[int] = 1
PIPELINE_STATS_SCHEMA_VERSION: Final[int] = 4
CANARY_SCHEMA_V1: Final[int] = 1
CANARY_SCHEMA_V2: Final[int] = 2
SUPPORTED_CANARY_SCHEMA_VERSIONS: Final[tuple[int, ...]] = (
    CANARY_SCHEMA_V1,
    CANARY_SCHEMA_V2,
)
SCOPED_CANARY_DEFAULT_GATE: Final[str] = "diagnostic"
SCOPED_CANARY_HARD_GATE: Final[str] = "hard"
SCOPED_CANARY_ALLOWED_GATES: Final[frozenset[str]] = frozenset({
    SCOPED_CANARY_DEFAULT_GATE,
    SCOPED_CANARY_HARD_GATE,
})

DEFAULT_MINIMUM_OUTPUT_RULES: Final[int] = 1_000_000
DEFAULT_SOURCE_FAILED_STALE_MINIMUM: Final[int] = 3
DEFAULT_SOURCE_FALLBACK_STALE_MINIMUM: Final[int] = 8
DEFAULT_SOURCE_HARD_RATIO: Final[float] = 0.10
DEFAULT_PREVIOUS_EXTREME_DROP_RATIO: Final[float] = 0.25
DEFAULT_PREVIOUS_EXTREME_INCREASE_RATIO: Final[float] = 1.00
DEFAULT_PREVIOUS_MODERATE_DELTA_RATIO: Final[float] = 0.10
DEFAULT_PREVIOUS_EXTREME_ABSOLUTE_DELTA: Final[int] = 1_000_000

SOURCE_HEALTH_STATUSES: Final[tuple[str, ...]] = (
    "failed",
    "fallback_cache",
    "fresh_fetch",
    "stale_cache",
    "validated_cache",
)
PIPELINE_DETAIL_FINDING_CODES: Final[frozenset[str]] = frozenset({
    "pipeline_stats_invalid",
    "pipeline_statistics_invalid",
    "pipeline_output_count_missing",
    "pipeline_output_count_invalid",
    "pipeline_output_count_mismatch",
})
SCOPED_CANARY_EXPECT_BLOCKED: Final[str] = "blocked"
SCOPED_CANARY_EXPECT_ALLOWED: Final[str] = "allowed"
SCOPED_CANARY_ALLOWED_EXPECTATIONS: Final[frozenset[str]] = frozenset({
    SCOPED_CANARY_EXPECT_ALLOWED,
    SCOPED_CANARY_EXPECT_BLOCKED,
})
SCOPED_CANARY_ALLOWED_SCOPES: Final[frozenset[str]] = frozenset({
    SCOPE_APEX,
    SCOPE_APEX_AND_SUBDOMAINS,
    SCOPE_EXACT_HOST,
    SCOPE_SUBDOMAIN,
    SCOPE_UNSCOPED_GLOBAL,
    SCOPE_WILDCARD_APEX_ALLOWED,
    SCOPE_WILDCARD_CHILD,
})
SCOPED_CANARY_ALLOWED_FIELDS: Final[frozenset[str]] = frozenset({
    "domain",
    "expect",
    "gate",
    "name",
    "scope",
})

Finding = dict[str, object]


# =============================================================================
# DATA STRUCTURES
# =============================================================================


@dataclass(frozen=True, slots=True)
class ReleaseThresholds:
    """Numeric release validation thresholds."""

    minimum_output_rules: int = DEFAULT_MINIMUM_OUTPUT_RULES
    source_failed_stale_minimum: int = DEFAULT_SOURCE_FAILED_STALE_MINIMUM
    source_fallback_stale_minimum: int = DEFAULT_SOURCE_FALLBACK_STALE_MINIMUM
    source_hard_ratio: float = DEFAULT_SOURCE_HARD_RATIO
    previous_extreme_drop_ratio: float = DEFAULT_PREVIOUS_EXTREME_DROP_RATIO
    previous_extreme_increase_ratio: float = DEFAULT_PREVIOUS_EXTREME_INCREASE_RATIO
    previous_moderate_delta_ratio: float = DEFAULT_PREVIOUS_MODERATE_DELTA_RATIO
    previous_extreme_absolute_delta: int = DEFAULT_PREVIOUS_EXTREME_ABSOLUTE_DELTA


DEFAULT_THRESHOLDS: Final[ReleaseThresholds] = ReleaseThresholds()


@dataclass(slots=True)
class ValidationSummary:
    """Versioned validation summary data used for JSON and Markdown reports."""

    errors: list[Finding] = field(default_factory=list)
    warnings: list[Finding] = field(default_factory=list)
    schema_version: int = VALIDATION_SUMMARY_SCHEMA_VERSION
    version: str = __version__
    generated_at: str = ""
    thresholds: dict[str, object] = field(default_factory=dict)
    counts: dict[str, int] = field(default_factory=dict)
    source_health: dict[str, object] = field(default_factory=dict)
    syntax: dict[str, object] = field(default_factory=dict)
    canaries: dict[str, object] = field(default_factory=dict)
    previous_release: dict[str, object] = field(default_factory=dict)
    release_evidence: dict[str, object] = field(default_factory=dict)

    @property
    def status(self) -> str:
        """Return failed when any hard validation error exists."""
        return "failed" if self.errors else "passed"

    def to_dict(self) -> dict[str, object]:
        """Return the JSON-serializable summary shape."""
        return {
            "schema_version": self.schema_version,
            "version": self.version,
            "generated_at": self.generated_at,
            "status": self.status,
            "errors": self.errors,
            "warnings": self.warnings,
            "thresholds": self.thresholds,
            "counts": self.counts,
            "source_health": self.source_health,
            "syntax": self.syntax,
            "canaries": self.canaries,
            "previous_release": self.previous_release,
            "release_evidence": self.release_evidence,
        }


@dataclass(frozen=True, slots=True)
class ValidationRunResult:
    """CLI-style validation result."""

    summary: ValidationSummary
    exit_code: int


@dataclass(frozen=True, slots=True)
class OutputScan:
    """Result of scanning the generated output artifact."""

    line_count: int
    errors: list[Finding]
    blocked_domains: set[str]
    wildcard_domains: set[str]
    rules: tuple[str, ...]
    coverage_records: tuple[CoverageRecord, ...]
    syntax: dict[str, object]


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def _utc_now() -> str:
    """Return the current UTC timestamp in report format."""
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def _finding(code: str, message: str, **details: object) -> Finding:
    """Build a stable finding object."""
    finding: Finding = {"code": code, "message": message}
    if details:
        finding["details"] = details
    return finding


def _thresholds_to_dict(thresholds: ReleaseThresholds) -> dict[str, object]:
    """Return thresholds as a JSON-compatible dictionary."""
    return {
        "minimum_output_rules": thresholds.minimum_output_rules,
        "source_failed_stale_minimum": thresholds.source_failed_stale_minimum,
        "source_fallback_stale_minimum": thresholds.source_fallback_stale_minimum,
        "source_hard_ratio": thresholds.source_hard_ratio,
        "previous_extreme_drop_ratio": thresholds.previous_extreme_drop_ratio,
        "previous_extreme_increase_ratio": thresholds.previous_extreme_increase_ratio,
        "previous_moderate_delta_ratio": thresholds.previous_moderate_delta_ratio,
        "previous_extreme_absolute_delta": thresholds.previous_extreme_absolute_delta,
    }


def _load_json(path: Path, description: str) -> dict[str, object]:
    """Load a JSON object from disk."""
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        msg = f"{description} must be a JSON object: {path}"
        raise ValueError(msg)
    return data


def _load_pipeline_stats(path: Path) -> tuple[dict[str, object], list[Finding]]:
    """Load pipeline stats as a recoverable validation input."""
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError) as exc:
        return {}, [
            _finding(
                "pipeline_stats_invalid",
                "Pipeline-stats report could not be loaded",
                pipeline_stats_path=str(path),
                error=str(exc),
            )
        ]

    if not isinstance(data, dict):
        return {}, [
            _finding(
                "pipeline_stats_invalid",
                "Pipeline-stats report must be a JSON object",
                pipeline_stats_path=str(path),
                actual_type=type(data).__name__,
            )
        ]

    return data, []


def _atomic_write_text(path: Path, text: str) -> None:
    """Write text through an atomic sibling temp file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_suffix(".tmp")
    with open(temp_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    temp_path.replace(path)


def _atomic_write_json(path: Path, data: dict[str, object]) -> None:
    """Write JSON through an atomic sibling temp file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_suffix(".tmp")
    with open(temp_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, sort_keys=True)
        f.write("\n")
    temp_path.replace(path)


def _details_with_canaries_path(
    canaries_path: Path | None,
    **details: object,
) -> dict[str, object]:
    """Return finding details with an optional canary config path."""
    if canaries_path is not None:
        details["canaries_path"] = str(canaries_path)
    return details


def _read_non_empty_lines(path: Path) -> tuple[str, ...]:
    """Read stripped, non-empty lines from a release output file."""
    with open(path, encoding="utf-8-sig", errors="replace") as f:
        return tuple(line.strip() for line in f if line.strip())


def _non_empty_line_count(path: Path) -> int:
    """Count non-empty lines in a rule output file."""
    return len(_read_non_empty_lines(path))


def _canonicalize_domain(domain: str) -> str:
    """Return the release validator's canonical domain key."""
    return domain.lower().strip().rstrip(".")


def _source_health_counts(report: dict[str, object]) -> tuple[int, dict[str, int]]:
    """Extract stable source-health totals from a report."""
    source_count = int(report.get("source_count") or 0)
    totals = report.get("totals_by_status")
    counts = {status: 0 for status in SOURCE_HEALTH_STATUSES}

    if isinstance(totals, dict):
        for status in SOURCE_HEALTH_STATUSES:
            counts[status] = int(totals.get(status, 0))

    if source_count <= 0:
        sources = report.get("sources")
        if isinstance(sources, list):
            source_count = len(sources)
            counts = {status: 0 for status in SOURCE_HEALTH_STATUSES}
            for source in sources:
                if isinstance(source, dict):
                    status = str(source.get("status", ""))
                    if status in counts:
                        counts[status] += 1

    return source_count, counts


def _source_hard_limit(total_sources: int, minimum: int, ratio: float) -> int:
    """Calculate a hard limit from source count, floor, and ratio."""
    return max(minimum, math.ceil(total_sources * ratio))


def _validate_report_schema_versions(
    source_health: dict[str, object],
    pipeline_stats: dict[str, object],
    canaries: dict[str, object],
    *,
    validate_pipeline_stats: bool = True,
) -> list[Finding]:
    """Return hard errors for unsupported operational report schema versions."""
    _ = canaries
    errors: list[Finding] = []
    if source_health.get("schema_version") != SOURCE_HEALTH_SCHEMA_VERSION:
        errors.append(_finding("source_health_schema_version", "Unsupported source-health schema"))
    if (
        validate_pipeline_stats
        and pipeline_stats.get("schema_version") != PIPELINE_STATS_SCHEMA_VERSION
    ):
        errors.append(_finding(
            "pipeline_stats_schema_version",
            "Unsupported pipeline-stats schema",
        ))
    return errors


def _extract_pipeline_output_count(
    pipeline_stats: dict[str, object],
    pipeline_stats_path: Path,
) -> tuple[int | None, list[Finding]]:
    """Extract a trusted statistics.lines_output value from schema-versioned stats."""
    schema_version = pipeline_stats.get("schema_version")
    if schema_version != PIPELINE_STATS_SCHEMA_VERSION:
        return None, []

    statistics = pipeline_stats.get("statistics")
    if not isinstance(statistics, dict):
        return None, [
            _finding(
                "pipeline_statistics_invalid",
                "Pipeline statistics object is missing or invalid",
                pipeline_stats_path=str(pipeline_stats_path),
                schema_version=schema_version,
                field="statistics",
            )
        ]

    if "lines_output" not in statistics:
        return None, [
            _finding(
                "pipeline_output_count_missing",
                "Pipeline statistics is missing statistics.lines_output",
                pipeline_stats_path=str(pipeline_stats_path),
                schema_version=schema_version,
                field="statistics.lines_output",
            )
        ]

    value = statistics["lines_output"]
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        return None, [
            _finding(
                "pipeline_output_count_invalid",
                "Pipeline statistics.lines_output must be a non-negative integer",
                pipeline_stats_path=str(pipeline_stats_path),
                schema_version=schema_version,
                field="statistics.lines_output",
                value=value,
            )
        ]

    return value, []


def _validate_canary_schema(
    canaries: dict[str, object],
    canaries_path: Path | None = None,
) -> list[Finding]:
    """Return hard errors for unsupported or malformed canary config schemas."""
    schema_version = canaries.get("schema_version")
    if (
        isinstance(schema_version, bool)
        or not isinstance(schema_version, int)
        or schema_version not in SUPPORTED_CANARY_SCHEMA_VERSIONS
    ):
        return [
            _finding(
                "canary_schema_version",
                "Unsupported canary schema",
                **_details_with_canaries_path(
                    canaries_path,
                    field="schema_version",
                    schema_version=schema_version,
                    expected_versions=list(SUPPORTED_CANARY_SCHEMA_VERSIONS),
                ),
            )
        ]

    errors: list[Finding] = []
    if schema_version == CANARY_SCHEMA_V1:
        for field_name in ("must_block", "must_allow"):
            if not isinstance(canaries.get(field_name), list):
                errors.append(_finding(
                    "canary_config_invalid",
                    "Canary config must define domain lists",
                    **_details_with_canaries_path(
                        canaries_path,
                        field=field_name,
                        schema_version=schema_version,
                        expected="list",
                    ),
                ))
        return errors

    for field_name in ("must_block", "must_allow"):
        if field_name in canaries and not isinstance(canaries.get(field_name), list):
            errors.append(_finding(
                "canary_config_invalid",
                "Schema v2 canary domain field must be a list when present",
                **_details_with_canaries_path(
                    canaries_path,
                    field=field_name,
                    schema_version=schema_version,
                    expected="list",
                ),
            ))

    scoped_canaries = canaries.get("scoped_canaries", [])
    if not isinstance(scoped_canaries, list):
        errors.append(_finding(
            "canary_config_invalid",
            "Schema v2 scoped_canaries must be a list when present",
            **_details_with_canaries_path(
                canaries_path,
                field="scoped_canaries",
                schema_version=schema_version,
                expected="list",
            ),
        ))
    return errors


def _validate_scoped_canary_record(
    record: object,
    index: int,
    canaries_path: Path | None = None,
) -> tuple[dict[str, object] | None, list[Finding]]:
    """Validate and normalize one schema v2 scoped canary record."""
    field_prefix = f"scoped_canaries[{index}]"
    if not isinstance(record, dict):
        return None, [
            _finding(
                "canary_scoped_config_invalid",
                "Scoped canary record must be a JSON object",
                **_details_with_canaries_path(
                    canaries_path,
                    field=field_prefix,
                    expected="object",
                ),
            )
        ]

    unknown_fields = sorted(set(record) - SCOPED_CANARY_ALLOWED_FIELDS)
    if unknown_fields:
        return None, [
            _finding(
                "canary_scoped_config_invalid",
                "Scoped canary record contains an unsupported field",
                **_details_with_canaries_path(
                    canaries_path,
                    field=f"{field_prefix}.{unknown_fields[0]}",
                    expected=sorted(SCOPED_CANARY_ALLOWED_FIELDS),
                ),
            )
        ]

    name = record.get("name")
    if name is not None and not isinstance(name, str):
        return None, [
            _finding(
                "canary_scoped_config_invalid",
                "Scoped canary name must be a string when present",
                **_details_with_canaries_path(
                    canaries_path,
                    field=f"{field_prefix}.name",
                    expected="string",
                ),
            )
        ]

    domain = record.get("domain")
    if not isinstance(domain, str) or not domain.strip():
        return None, [
            _finding(
                "canary_scoped_config_invalid",
                "Scoped canary domain must be a non-empty string",
                **_details_with_canaries_path(
                    canaries_path,
                    field=f"{field_prefix}.domain",
                    expected="non-empty string",
                ),
            )
        ]

    expect = record.get("expect")
    if expect not in SCOPED_CANARY_ALLOWED_EXPECTATIONS:
        return None, [
            _finding(
                "canary_scoped_config_invalid",
                "Scoped canary expectation is unsupported",
                **_details_with_canaries_path(
                    canaries_path,
                    field=f"{field_prefix}.expect",
                    expected=sorted(SCOPED_CANARY_ALLOWED_EXPECTATIONS),
                ),
            )
        ]

    scope = record.get("scope")
    if scope not in SCOPED_CANARY_ALLOWED_SCOPES:
        return None, [
            _finding(
                "canary_scoped_config_invalid",
                "Scoped canary scope is unsupported",
                **_details_with_canaries_path(
                    canaries_path,
                    field=f"{field_prefix}.scope",
                    expected=sorted(SCOPED_CANARY_ALLOWED_SCOPES),
                ),
            )
        ]

    gate = record.get("gate", SCOPED_CANARY_DEFAULT_GATE)
    if gate not in SCOPED_CANARY_ALLOWED_GATES:
        return None, [
            _finding(
                "canary_scoped_config_invalid",
                "Scoped canary gate is unsupported",
                **_details_with_canaries_path(
                    canaries_path,
                    field=f"{field_prefix}.gate",
                    expected=sorted(SCOPED_CANARY_ALLOWED_GATES),
                ),
            )
        ]

    normalized: dict[str, object] = {
        "name": name,
        "domain": _canonicalize_domain(domain),
        "expect": expect,
        "scope": scope,
        "gate": gate,
    }
    return normalized, []


def _validate_scoped_canaries(
    canaries: dict[str, object],
    canaries_path: Path | None = None,
) -> tuple[list[dict[str, object]], list[Finding]]:
    """Validate and normalize all schema v2 scoped canaries."""
    scoped_canaries = canaries.get("scoped_canaries", [])
    if not scoped_canaries:
        return [], []

    normalized_records: list[dict[str, object]] = []
    errors: list[Finding] = []
    if not isinstance(scoped_canaries, list):
        return normalized_records, [
            _finding(
                "canary_config_invalid",
                "Schema v2 scoped_canaries must be a list when present",
                **_details_with_canaries_path(
                    canaries_path,
                    field="scoped_canaries",
                    expected="list",
                ),
            )
        ]

    for index, record in enumerate(scoped_canaries):
        normalized, record_errors = _validate_scoped_canary_record(
            record,
            index,
            canaries_path,
        )
        errors.extend(record_errors)
        if normalized is not None:
            normalized_records.append(normalized)

    return normalized_records, errors


# =============================================================================
# SOURCE HEALTH VALIDATION
# =============================================================================


def validate_source_health(
    report: dict[str, object],
    thresholds: ReleaseThresholds,
) -> tuple[list[Finding], list[Finding], dict[str, object]]:
    """Validate source-health report totals against two-tier release gates."""
    total_sources, counts = _source_health_counts(report)
    failed_stale = counts["failed"] + counts["stale_cache"]
    fallback_stale = counts["fallback_cache"] + counts["stale_cache"]
    failed_stale_limit = _source_hard_limit(
        total_sources,
        thresholds.source_failed_stale_minimum,
        thresholds.source_hard_ratio,
    )
    fallback_stale_limit = _source_hard_limit(
        total_sources,
        thresholds.source_fallback_stale_minimum,
        thresholds.source_hard_ratio,
    )

    errors: list[Finding] = []
    warnings: list[Finding] = []
    if failed_stale > failed_stale_limit:
        errors.append(_finding(
            "source_health_catastrophic_failed_stale",
            "Failed plus stale sources exceed the hard release threshold",
            failed_stale=failed_stale,
            limit=failed_stale_limit,
        ))
    if fallback_stale > fallback_stale_limit:
        errors.append(_finding(
            "source_health_catastrophic_fallback_stale",
            "Fallback plus stale sources exceed the hard release threshold",
            fallback_stale=fallback_stale,
            limit=fallback_stale_limit,
        ))

    degraded = counts["failed"] + counts["fallback_cache"] + counts["stale_cache"]
    if degraded and not errors:
        warnings.append(_finding(
            "source_health_degraded",
            "One or more sources used fallback cache, stale cache, or failed",
            degraded_sources=degraded,
        ))

    details = {
        "source_count": total_sources,
        "totals_by_status": counts,
        "failed_stale": failed_stale,
        "fallback_stale": fallback_stale,
        "failed_stale_hard_limit": failed_stale_limit,
        "fallback_stale_hard_limit": fallback_stale_limit,
    }
    return errors, warnings, details


# =============================================================================
# OUTPUT SYNTAX AND CANARY VALIDATION
# =============================================================================


def _add_blocked_domain(
    line: str,
    blocked_domains: set[str],
    wildcard_domains: set[str],
) -> None:
    """Record domain coverage represented by an emitted blocking line."""
    domain, _modifiers, is_exception, is_wildcard = extract_abp_info(line)
    if domain and not is_exception:
        target = wildcard_domains if is_wildcard else blocked_domains
        target.add(domain)
        return

    if line.startswith("@@"):
        return

    ip, hosts_domains = extract_hosts_info(line)
    if ip:
        for host_domain in hosts_domains:
            blocked_domains.add(_canonicalize_domain(host_domain))
        return

    if PLAIN_DOMAIN_PATTERN.match(line):
        domain = _canonicalize_domain(line)
        if domain and domain not in LOCAL_HOSTNAMES:
            blocked_domains.add(domain)


def scan_output(output_path: Path) -> OutputScan:
    """Scan emitted output for syntax errors and canary coverage indexes."""
    errors: list[Finding] = []
    blocked_domains: set[str] = set()
    wildcard_domains: set[str] = set()
    rules: list[str] = []
    line_count = 0
    invalid_count = 0
    url_path_count = 0
    unsupported_modifier_count = 0
    exception_count = 0

    with open(output_path, encoding="utf-8-sig", errors="replace") as f:
        for line_number, raw_line in enumerate(f, start=1):
            line = raw_line.strip()
            if not line:
                continue

            line_count += 1
            rules.append(line)
            syntax = classify_rule_syntax(line)
            if syntax.is_exception:
                exception_count += 1
                errors.append(_finding(
                    "output_exception_rule",
                    "Exception rules must not be emitted in the release artifact",
                    line_number=line_number,
                    rule=line,
                ))
            if syntax.is_invalid:
                invalid_count += 1
                errors.append(_finding(
                    "output_invalid_syntax",
                    "Invalid emitted rule syntax",
                    line_number=line_number,
                    rule=line,
                ))
            if syntax.has_url_path:
                url_path_count += 1
                errors.append(_finding(
                    "output_url_path",
                    "URL-path rule emitted in DNS blocklist output",
                    line_number=line_number,
                    rule=line,
                ))

            modifiers = set(syntax.modifier_names)
            if modifiers and has_unsupported_modifiers(modifiers):
                unsupported_modifier_count += 1
                errors.append(_finding(
                    "output_unsupported_modifier",
                    "Browser-only modifier emitted in DNS blocklist output",
                    line_number=line_number,
                    rule=line,
                    modifiers=sorted(modifiers),
                ))

            if not syntax.is_exception:
                _add_blocked_domain(line, blocked_domains, wildcard_domains)

    syntax_details = {
        "lines_scanned": line_count,
        "invalid_rules": invalid_count,
        "url_path_rules": url_path_count,
        "unsupported_modifier_rules": unsupported_modifier_count,
        "exception_rules": exception_count,
    }
    return OutputScan(
        line_count=line_count,
        errors=errors,
        blocked_domains=blocked_domains,
        wildcard_domains=wildcard_domains,
        rules=tuple(rules),
        coverage_records=coverage_records_from_rules(rules),
        syntax=syntax_details,
    )


def _domain_is_blocked(
    domain: str,
    blocked_domains: set[str],
    wildcard_domains: set[str],
) -> bool:
    """Return True when emitted domain or parent coverage blocks a domain."""
    canonical_domain = _canonicalize_domain(domain)
    if canonical_domain in blocked_domains:
        return True

    for parent in walk_parent_domains(canonical_domain):
        if parent in blocked_domains:
            return True

    return any(
        canonical_domain.endswith(f".{wildcard_domain}")
        for wildcard_domain in wildcard_domains
    )


def _record_blocks_scoped_domain(
    record: CoverageRecord,
    domain: str,
    scope: str,
) -> bool:
    """Return True when a coverage record blocks a scoped canary target."""
    if record.effect != COVERAGE_EFFECT_BLOCK:
        return False
    if scope == SCOPE_WILDCARD_APEX_ALLOWED:
        return record_covers_canary_scope(record, domain, SCOPE_APEX)
    return record_covers_canary_scope(record, domain, scope)


def _record_matches_scoped_evidence(
    record: CoverageRecord,
    domain: str,
    scope: str,
) -> bool:
    """Return True when a coverage record is useful evidence for a scoped canary."""
    if scope == SCOPE_WILDCARD_APEX_ALLOWED:
        return record_covers_canary_scope(record, domain, scope) or _record_blocks_scoped_domain(
            record,
            domain,
            scope,
        )
    return record_covers_canary_scope(record, domain, scope)


def _evaluate_scoped_canaries(
    scoped_canaries: list[dict[str, object]],
    coverage_records: tuple[CoverageRecord, ...],
) -> tuple[list[Finding], list[dict[str, object]]]:
    """Evaluate schema v2 scoped canaries against conservative coverage records."""
    errors: list[Finding] = []
    results: list[dict[str, object]] = []

    for canary in scoped_canaries:
        domain = str(canary["domain"])
        expect = str(canary["expect"])
        scope = str(canary["scope"])
        gate = str(canary["gate"])
        name = canary.get("name")
        matched = any(
            _record_matches_scoped_evidence(record, domain, scope)
            for record in coverage_records
        )
        blocked = any(
            _record_blocks_scoped_domain(record, domain, scope)
            for record in coverage_records
        )
        passed = blocked if expect == SCOPED_CANARY_EXPECT_BLOCKED else not blocked
        result: dict[str, object] = {
            "name": name,
            "domain": domain,
            "expect": expect,
            "scope": scope,
            "gate": gate,
            "matched": matched,
            "blocked": blocked,
            "status": "passed" if passed else "failed",
        }
        results.append(result)
        if passed or gate != SCOPED_CANARY_HARD_GATE:
            continue
        if expect == SCOPED_CANARY_EXPECT_BLOCKED:
            errors.append(_finding(
                "canary_scoped_block_missing",
                "Hard scoped must-block canary is not covered by emitted output",
                domain=domain,
                scope=scope,
                gate=gate,
                name=name,
            ))
        else:
            errors.append(_finding(
                "canary_scoped_allow_blocked",
                "Hard scoped must-allow canary is blocked by emitted output",
                domain=domain,
                scope=scope,
                gate=gate,
                name=name,
            ))

    return errors, results


def validate_canaries(
    canaries: dict[str, object],
    blocked_domains: set[str],
    wildcard_domains: set[str],
    *,
    coverage_records: tuple[CoverageRecord, ...] = (),
    canaries_path: Path | None = None,
) -> tuple[list[Finding], dict[str, object]]:
    """Validate simple and scoped canary domains."""
    schema_errors = _validate_canary_schema(canaries, canaries_path)
    if schema_errors:
        return schema_errors, {}

    schema_version = int(canaries["schema_version"])
    errors: list[Finding] = []
    must_block = canaries.get("must_block", [])
    must_allow = canaries.get("must_allow", [])
    if not isinstance(must_block, list) or not isinstance(must_allow, list):
        return [
            _finding(
                "canary_config_invalid",
                "Canary config must define domain lists",
                **_details_with_canaries_path(canaries_path, field="must_block|must_allow"),
            )
        ], {}

    must_block_results: list[dict[str, object]] = []
    must_allow_results: list[dict[str, object]] = []
    for domain in must_block:
        domain_text = str(domain)
        blocked = _domain_is_blocked(domain_text, blocked_domains, wildcard_domains)
        must_block_results.append({"domain": domain_text, "blocked": blocked})
        if not blocked:
            errors.append(_finding(
                "canary_must_block_missing",
                "Must-block canary is not covered by emitted output",
                domain=domain_text,
            ))

    for domain in must_allow:
        domain_text = str(domain)
        blocked = _domain_is_blocked(domain_text, blocked_domains, wildcard_domains)
        must_allow_results.append({"domain": domain_text, "blocked": blocked})
        if blocked:
            errors.append(_finding(
                "canary_must_allow_blocked",
                "Must-allow canary is blocked by emitted output",
                domain=domain_text,
            ))

    scoped_canaries, scoped_config_errors = _validate_scoped_canaries(canaries, canaries_path)
    if scoped_config_errors:
        return scoped_config_errors, {}

    scoped_errors, scoped_results = _evaluate_scoped_canaries(
        scoped_canaries,
        coverage_records,
    )
    errors.extend(scoped_errors)

    details: dict[str, object] = {
        "schema_version": schema_version,
        "must_block": must_block_results,
        "must_allow": must_allow_results,
    }
    if schema_version == CANARY_SCHEMA_V2 or scoped_results:
        details["scoped"] = scoped_results
    return errors, details


def _release_evidence_payload(
    *,
    current_rules: tuple[str, ...],
    previous_rules: tuple[str, ...] | None,
    source_health: dict[str, object],
    scoped_canaries: object,
    coverage_records: tuple[CoverageRecord, ...],
    evidence_json_path: Path | None = None,
) -> tuple[dict[str, object], dict[str, object] | None]:
    """Build diagnostic-only release evidence and optional sidecar payload."""
    source_health_context = compact_source_health_context(source_health)
    sidecar_payload: dict[str, object] | None = None

    if previous_rules is not None:
        churn = compare_membership(current_rules, previous_rules)
        churn_details = membership_churn_to_dict(churn)
        membership_churn: dict[str, object] = {
            "available": True,
            **churn_details,
        }
        output_fingerprints: dict[str, object] = {
            "current": churn.current_fingerprint,
            "previous": churn.previous_fingerprint,
            "added": churn.added_fingerprint,
            "removed": churn.removed_fingerprint,
        }
    else:
        churn = None
        membership_churn = {
            "available": False,
            "current_count": len(current_rules),
            "previous_count": None,
            "added_count": None,
            "removed_count": None,
        }
        output_fingerprints = {
            "current": fingerprint_membership(current_rules),
            "previous": None,
            "added": None,
            "removed": None,
        }

    sidecar: dict[str, object] = {"available": False, "path": None}
    if evidence_json_path is not None:
        sidecar = {"available": True, "path": str(evidence_json_path)}
        sidecar_payload = render_diagnostic_sidecar(
            membership_churn=churn,
            source_health_context=source_health_context,
            coverage_records=coverage_records,
        )

    return (
        {
            "schema_version": RELEASE_EVIDENCE_SCHEMA_VERSION,
            "membership_churn": membership_churn,
            "output_fingerprints": output_fingerprints,
            "source_health_context": source_health_context,
            "scoped_canaries": scoped_canaries if isinstance(scoped_canaries, list) else [],
            "sidecar": sidecar,
        },
        sidecar_payload,
    )


# =============================================================================
# PREVIOUS RELEASE VALIDATION
# =============================================================================


def validate_previous_output_delta(
    current_count: int,
    previous_count: int,
    thresholds: ReleaseThresholds = DEFAULT_THRESHOLDS,
) -> ValidationSummary:
    """Validate previous-release output count movement."""
    errors: list[Finding] = []
    warnings: list[Finding] = []
    absolute_delta = current_count - previous_count
    absolute_delta_magnitude = abs(absolute_delta)

    previous_release: dict[str, object] = {
        "available": True,
        "current_count": current_count,
        "previous_count": previous_count,
        "absolute_delta": absolute_delta,
        "relative_delta": None,
    }

    if previous_count <= 0:
        warnings.append(_finding(
            "previous_output_empty",
            "Previous release output is empty; delta comparison skipped",
        ))
        previous_release["available"] = False
        return ValidationSummary(
            errors=errors,
            warnings=warnings,
            generated_at=_utc_now(),
            thresholds=_thresholds_to_dict(thresholds),
            counts={"current_output_rules": current_count},
            previous_release=previous_release,
        )

    relative_delta = absolute_delta_magnitude / previous_count
    previous_release["relative_delta"] = round(relative_delta, 6)

    if current_count < previous_count:
        drop_ratio = (previous_count - current_count) / previous_count
        if drop_ratio > thresholds.previous_extreme_drop_ratio:
            errors.append(_finding(
                "previous_output_extreme_drop",
                "Current output dropped beyond the hard release threshold",
                drop_ratio=round(drop_ratio, 6),
            ))
    else:
        increase_ratio = (current_count - previous_count) / previous_count
        if increase_ratio > thresholds.previous_extreme_increase_ratio:
            errors.append(_finding(
                "previous_output_extreme_increase",
                "Current output increased beyond the hard release threshold",
                increase_ratio=round(increase_ratio, 6),
            ))

    if absolute_delta_magnitude > thresholds.previous_extreme_absolute_delta:
        errors.append(_finding(
            "previous_output_extreme_absolute_delta",
            "Current output absolute delta exceeds the hard release threshold",
            absolute_delta=absolute_delta,
        ))

    if not errors and relative_delta > thresholds.previous_moderate_delta_ratio:
        warnings.append(_finding(
            "previous_output_moderate_delta",
            "Current output changed beyond the warning threshold",
            relative_delta=round(relative_delta, 6),
            absolute_delta=absolute_delta,
        ))

    return ValidationSummary(
        errors=errors,
        warnings=warnings,
        generated_at=_utc_now(),
        thresholds=_thresholds_to_dict(thresholds),
        counts={"current_output_rules": current_count},
        previous_release=previous_release,
    )


# =============================================================================
# REPORT RENDERING
# =============================================================================


def _render_markdown_finding(finding: Finding) -> list[str]:
    """Render one finding, with compact details for pipeline count diagnostics."""
    lines = [f"- `{finding['code']}`: {finding['message']}"]
    if finding["code"] not in PIPELINE_DETAIL_FINDING_CODES:
        return lines

    details = finding.get("details")
    if not isinstance(details, dict):
        return lines

    for key, value in details.items():
        lines.append(f"  - `{key}`: {value}")
    return lines


def render_markdown_summary(summary: ValidationSummary) -> str:
    """Render a concise Markdown triage report."""
    title_status = "Failed" if summary.errors else "Passed"
    lines = [
        f"## Release Validation: {title_status}",
        "",
        f"- Current output rules: {summary.counts.get('current_output_rules', 0):,}",
        f"- Errors: {len(summary.errors)}",
        f"- Warnings: {len(summary.warnings)}",
        "",
        "### Errors",
    ]

    if summary.errors:
        for item in summary.errors:
            lines.extend(_render_markdown_finding(item))
    else:
        lines.append("- None")

    lines.append("")
    lines.append("### Warnings")
    if summary.warnings:
        for item in summary.warnings:
            lines.extend(_render_markdown_finding(item))
    else:
        lines.append("- None")

    lines.append("")
    lines.append("### Thresholds")
    for key, value in summary.thresholds.items():
        lines.append(f"- `{key}`: {value}")

    evidence = summary.release_evidence
    if evidence:
        churn = evidence.get("membership_churn")
        fingerprints = evidence.get("output_fingerprints")
        source_context = evidence.get("source_health_context")
        scoped_canaries = evidence.get("scoped_canaries")
        sidecar = evidence.get("sidecar")

        lines.append("")
        lines.append("### Release Evidence")
        if isinstance(churn, dict) and churn.get("available") is True:
            lines.append(
                f"- Membership churn: {churn.get('added_count', 0)} added, "
                f"{churn.get('removed_count', 0)} removed"
            )
        else:
            lines.append("- Membership churn: unavailable")

        if isinstance(fingerprints, dict):
            current_fingerprint = str(fingerprints.get("current") or "unavailable")
            previous_fingerprint = str(fingerprints.get("previous") or "unavailable")
            lines.append(f"- Current fingerprint: {current_fingerprint[:12]}")
            lines.append(f"- Previous fingerprint: {previous_fingerprint[:12]}")

        if isinstance(source_context, dict):
            lines.append(
                f"- Source health context: {source_context.get('source_count', 0)} sources, "
                f"{source_context.get('degraded_sources', 0)} degraded"
            )

        if isinstance(scoped_canaries, list):
            lines.append(f"- Scoped canaries: {len(scoped_canaries)}")

        if isinstance(sidecar, dict) and sidecar.get("available") is True:
            lines.append(f"- Evidence sidecar: {sidecar.get('path')}")

    lines.append("")
    return "\n".join(lines)


def save_validation_reports(
    summary: ValidationSummary,
    summary_json_path: Path,
    summary_md_path: Path,
    evidence_json_path: Path | None = None,
    evidence_sidecar: dict[str, object] | None = None,
) -> None:
    """Write JSON and Markdown validation summaries atomically."""
    if evidence_json_path is not None and evidence_sidecar is not None:
        write_report_json(evidence_json_path, evidence_sidecar)
    _atomic_write_json(summary_json_path, summary.to_dict())
    _atomic_write_text(summary_md_path, render_markdown_summary(summary))


# =============================================================================
# MAIN VALIDATION FLOW
# =============================================================================


def validate_release(
    *,
    source_health_path: Path,
    pipeline_stats_path: Path,
    output_path: Path,
    canaries_path: Path,
    previous_output_path: Path | None = None,
    summary_json_path: Path | None = None,
    summary_md_path: Path | None = None,
    evidence_json_path: Path | None = None,
    thresholds: ReleaseThresholds = DEFAULT_THRESHOLDS,
) -> ValidationSummary:
    """Validate a release candidate and optionally write summary reports."""
    source_health = _load_json(source_health_path, "source-health report")
    pipeline_stats, pipeline_stats_load_errors = _load_pipeline_stats(pipeline_stats_path)
    canaries = _load_json(canaries_path, "canary config")

    errors = _validate_report_schema_versions(
        source_health,
        pipeline_stats,
        canaries,
        validate_pipeline_stats=not pipeline_stats_load_errors,
    )
    errors.extend(pipeline_stats_load_errors)
    warnings: list[Finding] = []
    pipeline_count, pipeline_count_errors = _extract_pipeline_output_count(
        pipeline_stats,
        pipeline_stats_path,
    )
    errors.extend(pipeline_count_errors)

    source_errors, source_warnings, source_details = validate_source_health(
        source_health,
        thresholds,
    )
    errors.extend(source_errors)
    warnings.extend(source_warnings)

    output_scan = scan_output(output_path)
    errors.extend(output_scan.errors)

    current_count = output_scan.line_count
    if pipeline_count is not None and pipeline_count != current_count:
        errors.append(_finding(
            "pipeline_output_count_mismatch",
            "Pipeline reported output count does not match scanned release artifact",
            pipeline_reported_output_rules=pipeline_count,
            scanned_output_rules=current_count,
            absolute_delta=abs(pipeline_count - current_count),
            pipeline_stats_path=str(pipeline_stats_path),
            schema_version=pipeline_stats.get("schema_version"),
            field="statistics.lines_output",
        ))

    if current_count < thresholds.minimum_output_rules:
        errors.append(_finding(
            "output_below_minimum_count",
            "Current output rule count is below the hard minimum",
            current_count=current_count,
            minimum=thresholds.minimum_output_rules,
        ))

    canary_errors, canary_details = validate_canaries(
        canaries,
        output_scan.blocked_domains,
        output_scan.wildcard_domains,
        coverage_records=output_scan.coverage_records,
        canaries_path=canaries_path,
    )
    errors.extend(canary_errors)

    previous_release: dict[str, object] = {
        "available": False,
        "current_count": current_count,
        "previous_count": None,
        "absolute_delta": None,
        "relative_delta": None,
    }
    previous_rules: tuple[str, ...] | None = None
    if previous_output_path and previous_output_path.exists():
        previous_rules = _read_non_empty_lines(previous_output_path)
        previous_count = len(previous_rules)
        previous_summary = validate_previous_output_delta(current_count, previous_count, thresholds)
        errors.extend(previous_summary.errors)
        warnings.extend(previous_summary.warnings)
        previous_release = previous_summary.previous_release
    else:
        warnings.append(_finding(
            "previous_output_unavailable",
            "Previous release output is unavailable; delta comparison skipped",
        ))

    counts = {"current_output_rules": current_count}
    if pipeline_count is not None:
        counts["pipeline_reported_output_rules"] = pipeline_count

    release_evidence, evidence_sidecar = _release_evidence_payload(
        current_rules=output_scan.rules,
        previous_rules=previous_rules,
        source_health=source_health,
        scoped_canaries=canary_details.get("scoped", []),
        coverage_records=output_scan.coverage_records,
        evidence_json_path=evidence_json_path,
    )

    summary = ValidationSummary(
        errors=errors,
        warnings=warnings,
        generated_at=_utc_now(),
        thresholds=_thresholds_to_dict(thresholds),
        counts=counts,
        source_health=source_details,
        syntax=output_scan.syntax,
        canaries=canary_details,
        previous_release=previous_release,
        release_evidence=release_evidence,
    )

    if summary_json_path and summary_md_path:
        save_validation_reports(
            summary,
            summary_json_path,
            summary_md_path,
            evidence_json_path=evidence_json_path,
            evidence_sidecar=evidence_sidecar,
        )

    return summary


def run_validation(
    *,
    source_health_path: Path,
    pipeline_stats_path: Path,
    output_path: Path,
    canaries_path: Path,
    previous_output_path: Path | None,
    summary_json_path: Path,
    summary_md_path: Path,
    evidence_json_path: Path | None = None,
    thresholds: ReleaseThresholds = DEFAULT_THRESHOLDS,
) -> ValidationRunResult:
    """Validate and return a CLI-style exit code."""
    summary = validate_release(
        source_health_path=source_health_path,
        pipeline_stats_path=pipeline_stats_path,
        output_path=output_path,
        canaries_path=canaries_path,
        previous_output_path=previous_output_path,
        summary_json_path=summary_json_path,
        summary_md_path=summary_md_path,
        evidence_json_path=evidence_json_path,
        thresholds=thresholds,
    )
    return ValidationRunResult(summary=summary, exit_code=1 if summary.errors else 0)


# =============================================================================
# CLI INTERFACE
# =============================================================================


def _parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(
        prog="scripts.release_validator",
        description="Validate release candidate safety before publishing.",
    )
    parser.add_argument("--source-health", required=True, help="Path to source-health JSON")
    parser.add_argument("--pipeline-stats", required=True, help="Path to pipeline-stats JSON")
    parser.add_argument("--output", required=True, help="Path to current merged output")
    parser.add_argument("--canaries", required=True, help="Path to release canaries JSON")
    parser.add_argument("--previous-output", help="Optional previous release output")
    parser.add_argument("--summary-json", required=True, help="Path for validation JSON summary")
    parser.add_argument("--summary-md", required=True, help="Path for validation Markdown summary")
    parser.add_argument("--evidence-json", help="Optional path for detailed release evidence JSON")
    parser.add_argument(
        "--minimum-output-rules",
        type=int,
        default=DEFAULT_MINIMUM_OUTPUT_RULES,
        help="Hard minimum emitted rule count",
    )
    return parser.parse_args()


def main() -> int:
    """CLI entry point."""
    args = _parse_args()
    previous_output = Path(args.previous_output) if args.previous_output else None
    evidence_json = Path(args.evidence_json) if args.evidence_json else None
    thresholds = ReleaseThresholds(minimum_output_rules=args.minimum_output_rules)

    try:
        result = run_validation(
            source_health_path=Path(args.source_health),
            pipeline_stats_path=Path(args.pipeline_stats),
            output_path=Path(args.output),
            canaries_path=Path(args.canaries),
            previous_output_path=previous_output,
            summary_json_path=Path(args.summary_json),
            summary_md_path=Path(args.summary_md),
            evidence_json_path=evidence_json,
            thresholds=thresholds,
        )
        if result.exit_code:
            print(f"Release validation failed with {len(result.summary.errors)} error(s)")
        else:
            print(f"Release validation passed with {len(result.summary.warnings)} warning(s)")
        return result.exit_code
    except Exception as e:
        print(f"\nERROR: {e}", file=sys.stderr)
        import traceback

        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
