#!/usr/bin/env python3
"""
release_validator.py - Release safety gates for generated blocklist artifacts.

This module consumes the operational reports generated by the downloader and
pipeline, scans the final output artifact, checks release canaries, and compares
against an optional previous release output.
"""

import argparse
import json
import math
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final

from scripts import __version__
from scripts.cleaner import has_unsupported_modifiers
from scripts.compiler import (
    LOCAL_HOSTNAMES,
    PLAIN_DOMAIN_PATTERN,
    extract_abp_info,
    extract_hosts_info,
    normalize_domain,
    walk_parent_domains,
)
from scripts.rule_syntax import classify_rule_syntax

# =============================================================================
# CONFIGURATION CONSTANTS
# =============================================================================

VALIDATION_SUMMARY_SCHEMA_VERSION: Final[int] = 1
SOURCE_HEALTH_SCHEMA_VERSION: Final[int] = 1
PIPELINE_STATS_SCHEMA_VERSION: Final[int] = 2

DEFAULT_MINIMUM_OUTPUT_RULES: Final[int] = 1_000_000
DEFAULT_SOURCE_FAILED_STALE_MINIMUM: Final[int] = 3
DEFAULT_SOURCE_FALLBACK_STALE_MINIMUM: Final[int] = 8
DEFAULT_SOURCE_HARD_RATIO: Final[float] = 0.10
DEFAULT_PREVIOUS_EXTREME_DROP_RATIO: Final[float] = 0.25
DEFAULT_PREVIOUS_EXTREME_INCREASE_RATIO: Final[float] = 1.00
DEFAULT_PREVIOUS_MODERATE_DELTA_RATIO: Final[float] = 0.10
DEFAULT_PREVIOUS_EXTREME_ABSOLUTE_DELTA: Final[int] = 1_000_000

SOURCE_HEALTH_STATUSES: Final[tuple[str, ...]] = (
    "failed",
    "fallback_cache",
    "fresh_fetch",
    "stale_cache",
    "validated_cache",
)

Finding = dict[str, object]


# =============================================================================
# DATA STRUCTURES
# =============================================================================


@dataclass(frozen=True, slots=True)
class ReleaseThresholds:
    """Numeric release validation thresholds."""

    minimum_output_rules: int = DEFAULT_MINIMUM_OUTPUT_RULES
    source_failed_stale_minimum: int = DEFAULT_SOURCE_FAILED_STALE_MINIMUM
    source_fallback_stale_minimum: int = DEFAULT_SOURCE_FALLBACK_STALE_MINIMUM
    source_hard_ratio: float = DEFAULT_SOURCE_HARD_RATIO
    previous_extreme_drop_ratio: float = DEFAULT_PREVIOUS_EXTREME_DROP_RATIO
    previous_extreme_increase_ratio: float = DEFAULT_PREVIOUS_EXTREME_INCREASE_RATIO
    previous_moderate_delta_ratio: float = DEFAULT_PREVIOUS_MODERATE_DELTA_RATIO
    previous_extreme_absolute_delta: int = DEFAULT_PREVIOUS_EXTREME_ABSOLUTE_DELTA


DEFAULT_THRESHOLDS: Final[ReleaseThresholds] = ReleaseThresholds()


@dataclass(slots=True)
class ValidationSummary:
    """Versioned validation summary data used for JSON and Markdown reports."""

    errors: list[Finding] = field(default_factory=list)
    warnings: list[Finding] = field(default_factory=list)
    schema_version: int = VALIDATION_SUMMARY_SCHEMA_VERSION
    version: str = __version__
    generated_at: str = ""
    thresholds: dict[str, object] = field(default_factory=dict)
    counts: dict[str, int] = field(default_factory=dict)
    source_health: dict[str, object] = field(default_factory=dict)
    syntax: dict[str, object] = field(default_factory=dict)
    canaries: dict[str, object] = field(default_factory=dict)
    previous_release: dict[str, object] = field(default_factory=dict)

    @property
    def status(self) -> str:
        """Return failed when any hard validation error exists."""
        return "failed" if self.errors else "passed"

    def to_dict(self) -> dict[str, object]:
        """Return the JSON-serializable summary shape."""
        return {
            "schema_version": self.schema_version,
            "version": self.version,
            "generated_at": self.generated_at,
            "status": self.status,
            "errors": self.errors,
            "warnings": self.warnings,
            "thresholds": self.thresholds,
            "counts": self.counts,
            "source_health": self.source_health,
            "syntax": self.syntax,
            "canaries": self.canaries,
            "previous_release": self.previous_release,
        }


@dataclass(frozen=True, slots=True)
class ValidationRunResult:
    """CLI-style validation result."""

    summary: ValidationSummary
    exit_code: int


@dataclass(frozen=True, slots=True)
class OutputScan:
    """Result of scanning the generated output artifact."""

    line_count: int
    errors: list[Finding]
    blocked_domains: set[str]
    wildcard_domains: set[str]
    syntax: dict[str, object]


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def _utc_now() -> str:
    """Return the current UTC timestamp in report format."""
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def _finding(code: str, message: str, **details: object) -> Finding:
    """Build a stable finding object."""
    finding: Finding = {"code": code, "message": message}
    if details:
        finding["details"] = details
    return finding


def _thresholds_to_dict(thresholds: ReleaseThresholds) -> dict[str, object]:
    """Return thresholds as a JSON-compatible dictionary."""
    return {
        "minimum_output_rules": thresholds.minimum_output_rules,
        "source_failed_stale_minimum": thresholds.source_failed_stale_minimum,
        "source_fallback_stale_minimum": thresholds.source_fallback_stale_minimum,
        "source_hard_ratio": thresholds.source_hard_ratio,
        "previous_extreme_drop_ratio": thresholds.previous_extreme_drop_ratio,
        "previous_extreme_increase_ratio": thresholds.previous_extreme_increase_ratio,
        "previous_moderate_delta_ratio": thresholds.previous_moderate_delta_ratio,
        "previous_extreme_absolute_delta": thresholds.previous_extreme_absolute_delta,
    }


def _load_json(path: Path, description: str) -> dict[str, object]:
    """Load a JSON object from disk."""
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        msg = f"{description} must be a JSON object: {path}"
        raise ValueError(msg)
    return data


def _atomic_write_text(path: Path, text: str) -> None:
    """Write text through an atomic sibling temp file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_suffix(".tmp")
    with open(temp_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    temp_path.replace(path)


def _atomic_write_json(path: Path, data: dict[str, object]) -> None:
    """Write JSON through an atomic sibling temp file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_suffix(".tmp")
    with open(temp_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, sort_keys=True)
        f.write("\n")
    temp_path.replace(path)


def _non_empty_line_count(path: Path) -> int:
    """Count non-empty lines in a rule output file."""
    with open(path, encoding="utf-8-sig", errors="replace") as f:
        return sum(1 for line in f if line.strip())


def _source_health_counts(report: dict[str, object]) -> tuple[int, dict[str, int]]:
    """Extract stable source-health totals from a report."""
    source_count = int(report.get("source_count") or 0)
    totals = report.get("totals_by_status")
    counts = {status: 0 for status in SOURCE_HEALTH_STATUSES}

    if isinstance(totals, dict):
        for status in SOURCE_HEALTH_STATUSES:
            counts[status] = int(totals.get(status, 0))

    if source_count <= 0:
        sources = report.get("sources")
        if isinstance(sources, list):
            source_count = len(sources)
            counts = {status: 0 for status in SOURCE_HEALTH_STATUSES}
            for source in sources:
                if isinstance(source, dict):
                    status = str(source.get("status", ""))
                    if status in counts:
                        counts[status] += 1

    return source_count, counts


def _source_hard_limit(total_sources: int, minimum: int, ratio: float) -> int:
    """Calculate a hard limit from source count, floor, and ratio."""
    return max(minimum, math.ceil(total_sources * ratio))


def _validate_report_schema_versions(
    source_health: dict[str, object],
    pipeline_stats: dict[str, object],
    canaries: dict[str, object],
) -> list[Finding]:
    """Return hard errors for unsupported report schema versions."""
    errors: list[Finding] = []
    if source_health.get("schema_version") != SOURCE_HEALTH_SCHEMA_VERSION:
        errors.append(_finding("source_health_schema_version", "Unsupported source-health schema"))
    if pipeline_stats.get("schema_version") != PIPELINE_STATS_SCHEMA_VERSION:
        errors.append(_finding(
            "pipeline_stats_schema_version",
            "Unsupported pipeline-stats schema",
        ))
    if canaries.get("schema_version") != 1:
        errors.append(_finding("canary_schema_version", "Unsupported canary schema"))
    return errors


# =============================================================================
# SOURCE HEALTH VALIDATION
# =============================================================================


def validate_source_health(
    report: dict[str, object],
    thresholds: ReleaseThresholds,
) -> tuple[list[Finding], list[Finding], dict[str, object]]:
    """Validate source-health report totals against two-tier release gates."""
    total_sources, counts = _source_health_counts(report)
    failed_stale = counts["failed"] + counts["stale_cache"]
    fallback_stale = counts["fallback_cache"] + counts["stale_cache"]
    failed_stale_limit = _source_hard_limit(
        total_sources,
        thresholds.source_failed_stale_minimum,
        thresholds.source_hard_ratio,
    )
    fallback_stale_limit = _source_hard_limit(
        total_sources,
        thresholds.source_fallback_stale_minimum,
        thresholds.source_hard_ratio,
    )

    errors: list[Finding] = []
    warnings: list[Finding] = []
    if failed_stale > failed_stale_limit:
        errors.append(_finding(
            "source_health_catastrophic_failed_stale",
            "Failed plus stale sources exceed the hard release threshold",
            failed_stale=failed_stale,
            limit=failed_stale_limit,
        ))
    if fallback_stale > fallback_stale_limit:
        errors.append(_finding(
            "source_health_catastrophic_fallback_stale",
            "Fallback plus stale sources exceed the hard release threshold",
            fallback_stale=fallback_stale,
            limit=fallback_stale_limit,
        ))

    degraded = counts["failed"] + counts["fallback_cache"] + counts["stale_cache"]
    if degraded and not errors:
        warnings.append(_finding(
            "source_health_degraded",
            "One or more sources used fallback cache, stale cache, or failed",
            degraded_sources=degraded,
        ))

    details = {
        "source_count": total_sources,
        "totals_by_status": counts,
        "failed_stale": failed_stale,
        "fallback_stale": fallback_stale,
        "failed_stale_hard_limit": failed_stale_limit,
        "fallback_stale_hard_limit": fallback_stale_limit,
    }
    return errors, warnings, details


# =============================================================================
# OUTPUT SYNTAX AND CANARY VALIDATION
# =============================================================================


def _add_blocked_domain(
    line: str,
    blocked_domains: set[str],
    wildcard_domains: set[str],
) -> None:
    """Record domain coverage represented by an emitted blocking line."""
    domain, _modifiers, is_exception, is_wildcard = extract_abp_info(line)
    if domain and not is_exception:
        target = wildcard_domains if is_wildcard else blocked_domains
        target.add(domain)
        return

    if line.startswith("@@"):
        return

    ip, hosts_domains = extract_hosts_info(line)
    if ip:
        for host_domain in hosts_domains:
            blocked_domains.add(normalize_domain(host_domain))
        return

    if PLAIN_DOMAIN_PATTERN.match(line):
        domain = normalize_domain(line)
        if domain and domain not in LOCAL_HOSTNAMES:
            blocked_domains.add(domain)


def scan_output(output_path: Path) -> OutputScan:
    """Scan emitted output for syntax errors and canary coverage indexes."""
    errors: list[Finding] = []
    blocked_domains: set[str] = set()
    wildcard_domains: set[str] = set()
    line_count = 0
    invalid_count = 0
    url_path_count = 0
    unsupported_modifier_count = 0
    exception_count = 0

    with open(output_path, encoding="utf-8-sig", errors="replace") as f:
        for line_number, raw_line in enumerate(f, start=1):
            line = raw_line.strip()
            if not line:
                continue

            line_count += 1
            syntax = classify_rule_syntax(line)
            if syntax.is_exception:
                exception_count += 1
                errors.append(_finding(
                    "output_exception_rule",
                    "Exception rules must not be emitted in the release artifact",
                    line_number=line_number,
                    rule=line,
                ))
            if syntax.is_invalid:
                invalid_count += 1
                errors.append(_finding(
                    "output_invalid_syntax",
                    "Invalid emitted rule syntax",
                    line_number=line_number,
                    rule=line,
                ))
            if syntax.has_url_path:
                url_path_count += 1
                errors.append(_finding(
                    "output_url_path",
                    "URL-path rule emitted in DNS blocklist output",
                    line_number=line_number,
                    rule=line,
                ))

            modifiers = set(syntax.modifier_names)
            if modifiers and has_unsupported_modifiers(modifiers):
                unsupported_modifier_count += 1
                errors.append(_finding(
                    "output_unsupported_modifier",
                    "Browser-only modifier emitted in DNS blocklist output",
                    line_number=line_number,
                    rule=line,
                    modifiers=sorted(modifiers),
                ))

            if not syntax.is_exception:
                _add_blocked_domain(line, blocked_domains, wildcard_domains)

    syntax_details = {
        "lines_scanned": line_count,
        "invalid_rules": invalid_count,
        "url_path_rules": url_path_count,
        "unsupported_modifier_rules": unsupported_modifier_count,
        "exception_rules": exception_count,
    }
    return OutputScan(
        line_count=line_count,
        errors=errors,
        blocked_domains=blocked_domains,
        wildcard_domains=wildcard_domains,
        syntax=syntax_details,
    )


def _domain_is_blocked(
    domain: str,
    blocked_domains: set[str],
    wildcard_domains: set[str],
) -> bool:
    """Return True when emitted domain or parent coverage blocks a domain."""
    normalized = normalize_domain(domain)
    if normalized in blocked_domains:
        return True

    for parent in walk_parent_domains(normalized):
        if parent in blocked_domains:
            return True

    return any(normalized.endswith(f".{wildcard_domain}") for wildcard_domain in wildcard_domains)


def validate_canaries(
    canaries: dict[str, object],
    blocked_domains: set[str],
    wildcard_domains: set[str],
) -> tuple[list[Finding], dict[str, object]]:
    """Validate must-block and must-allow canary domains."""
    errors: list[Finding] = []
    must_block = canaries.get("must_block")
    must_allow = canaries.get("must_allow")
    if not isinstance(must_block, list) or not isinstance(must_allow, list):
        return [
            _finding("canary_config_invalid", "Canary config must define domain lists")
        ], {}

    must_block_results: list[dict[str, object]] = []
    must_allow_results: list[dict[str, object]] = []
    for domain in must_block:
        domain_text = str(domain)
        blocked = _domain_is_blocked(domain_text, blocked_domains, wildcard_domains)
        must_block_results.append({"domain": domain_text, "blocked": blocked})
        if not blocked:
            errors.append(_finding(
                "canary_must_block_missing",
                "Must-block canary is not covered by emitted output",
                domain=domain_text,
            ))

    for domain in must_allow:
        domain_text = str(domain)
        blocked = _domain_is_blocked(domain_text, blocked_domains, wildcard_domains)
        must_allow_results.append({"domain": domain_text, "blocked": blocked})
        if blocked:
            errors.append(_finding(
                "canary_must_allow_blocked",
                "Must-allow canary is blocked by emitted output",
                domain=domain_text,
            ))

    return errors, {
        "must_block": must_block_results,
        "must_allow": must_allow_results,
    }


# =============================================================================
# PREVIOUS RELEASE VALIDATION
# =============================================================================


def validate_previous_output_delta(
    current_count: int,
    previous_count: int,
    thresholds: ReleaseThresholds = DEFAULT_THRESHOLDS,
) -> ValidationSummary:
    """Validate previous-release output count movement."""
    errors: list[Finding] = []
    warnings: list[Finding] = []
    absolute_delta = current_count - previous_count
    absolute_delta_magnitude = abs(absolute_delta)

    previous_release: dict[str, object] = {
        "available": True,
        "current_count": current_count,
        "previous_count": previous_count,
        "absolute_delta": absolute_delta,
        "relative_delta": None,
    }

    if previous_count <= 0:
        warnings.append(_finding(
            "previous_output_empty",
            "Previous release output is empty; delta comparison skipped",
        ))
        previous_release["available"] = False
        return ValidationSummary(
            errors=errors,
            warnings=warnings,
            generated_at=_utc_now(),
            thresholds=_thresholds_to_dict(thresholds),
            counts={"current_output_rules": current_count},
            previous_release=previous_release,
        )

    relative_delta = absolute_delta_magnitude / previous_count
    previous_release["relative_delta"] = round(relative_delta, 6)

    if current_count < previous_count:
        drop_ratio = (previous_count - current_count) / previous_count
        if drop_ratio > thresholds.previous_extreme_drop_ratio:
            errors.append(_finding(
                "previous_output_extreme_drop",
                "Current output dropped beyond the hard release threshold",
                drop_ratio=round(drop_ratio, 6),
            ))
    else:
        increase_ratio = (current_count - previous_count) / previous_count
        if increase_ratio > thresholds.previous_extreme_increase_ratio:
            errors.append(_finding(
                "previous_output_extreme_increase",
                "Current output increased beyond the hard release threshold",
                increase_ratio=round(increase_ratio, 6),
            ))

    if absolute_delta_magnitude > thresholds.previous_extreme_absolute_delta:
        errors.append(_finding(
            "previous_output_extreme_absolute_delta",
            "Current output absolute delta exceeds the hard release threshold",
            absolute_delta=absolute_delta,
        ))

    if not errors and relative_delta > thresholds.previous_moderate_delta_ratio:
        warnings.append(_finding(
            "previous_output_moderate_delta",
            "Current output changed beyond the warning threshold",
            relative_delta=round(relative_delta, 6),
            absolute_delta=absolute_delta,
        ))

    return ValidationSummary(
        errors=errors,
        warnings=warnings,
        generated_at=_utc_now(),
        thresholds=_thresholds_to_dict(thresholds),
        counts={"current_output_rules": current_count},
        previous_release=previous_release,
    )


# =============================================================================
# REPORT RENDERING
# =============================================================================


def render_markdown_summary(summary: ValidationSummary) -> str:
    """Render a concise Markdown triage report."""
    title_status = "Failed" if summary.errors else "Passed"
    lines = [
        f"## Release Validation: {title_status}",
        "",
        f"- Current output rules: {summary.counts.get('current_output_rules', 0):,}",
        f"- Errors: {len(summary.errors)}",
        f"- Warnings: {len(summary.warnings)}",
        "",
        "### Errors",
    ]

    if summary.errors:
        lines.extend(f"- `{item['code']}`: {item['message']}" for item in summary.errors)
    else:
        lines.append("- None")

    lines.append("")
    lines.append("### Warnings")
    if summary.warnings:
        lines.extend(f"- `{item['code']}`: {item['message']}" for item in summary.warnings)
    else:
        lines.append("- None")

    lines.append("")
    lines.append("### Thresholds")
    for key, value in summary.thresholds.items():
        lines.append(f"- `{key}`: {value}")

    lines.append("")
    return "\n".join(lines)


def save_validation_reports(
    summary: ValidationSummary,
    summary_json_path: Path,
    summary_md_path: Path,
) -> None:
    """Write JSON and Markdown validation summaries atomically."""
    _atomic_write_json(summary_json_path, summary.to_dict())
    _atomic_write_text(summary_md_path, render_markdown_summary(summary))


# =============================================================================
# MAIN VALIDATION FLOW
# =============================================================================


def validate_release(
    *,
    source_health_path: Path,
    pipeline_stats_path: Path,
    output_path: Path,
    canaries_path: Path,
    previous_output_path: Path | None = None,
    summary_json_path: Path | None = None,
    summary_md_path: Path | None = None,
    thresholds: ReleaseThresholds = DEFAULT_THRESHOLDS,
) -> ValidationSummary:
    """Validate a release candidate and optionally write summary reports."""
    source_health = _load_json(source_health_path, "source-health report")
    pipeline_stats = _load_json(pipeline_stats_path, "pipeline-stats report")
    canaries = _load_json(canaries_path, "canary config")

    errors = _validate_report_schema_versions(source_health, pipeline_stats, canaries)
    warnings: list[Finding] = []

    source_errors, source_warnings, source_details = validate_source_health(
        source_health,
        thresholds,
    )
    errors.extend(source_errors)
    warnings.extend(source_warnings)

    output_scan = scan_output(output_path)
    errors.extend(output_scan.errors)

    current_count = output_scan.line_count
    if current_count < thresholds.minimum_output_rules:
        errors.append(_finding(
            "output_below_minimum_count",
            "Current output rule count is below the hard minimum",
            current_count=current_count,
            minimum=thresholds.minimum_output_rules,
        ))

    canary_errors, canary_details = validate_canaries(
        canaries,
        output_scan.blocked_domains,
        output_scan.wildcard_domains,
    )
    errors.extend(canary_errors)

    previous_release: dict[str, object] = {
        "available": False,
        "current_count": current_count,
        "previous_count": None,
        "absolute_delta": None,
        "relative_delta": None,
    }
    if previous_output_path and previous_output_path.exists():
        previous_count = _non_empty_line_count(previous_output_path)
        previous_summary = validate_previous_output_delta(current_count, previous_count, thresholds)
        errors.extend(previous_summary.errors)
        warnings.extend(previous_summary.warnings)
        previous_release = previous_summary.previous_release
    else:
        warnings.append(_finding(
            "previous_output_unavailable",
            "Previous release output is unavailable; delta comparison skipped",
        ))

    stats = pipeline_stats.get("statistics", {})
    pipeline_count = 0
    if isinstance(stats, dict):
        pipeline_count = int(stats.get("lines_output", 0))

    summary = ValidationSummary(
        errors=errors,
        warnings=warnings,
        generated_at=_utc_now(),
        thresholds=_thresholds_to_dict(thresholds),
        counts={
            "current_output_rules": current_count,
            "pipeline_reported_output_rules": pipeline_count,
        },
        source_health=source_details,
        syntax=output_scan.syntax,
        canaries=canary_details,
        previous_release=previous_release,
    )

    if summary_json_path and summary_md_path:
        save_validation_reports(summary, summary_json_path, summary_md_path)

    return summary


def run_validation(
    *,
    source_health_path: Path,
    pipeline_stats_path: Path,
    output_path: Path,
    canaries_path: Path,
    previous_output_path: Path | None,
    summary_json_path: Path,
    summary_md_path: Path,
    thresholds: ReleaseThresholds = DEFAULT_THRESHOLDS,
) -> ValidationRunResult:
    """Validate and return a CLI-style exit code."""
    summary = validate_release(
        source_health_path=source_health_path,
        pipeline_stats_path=pipeline_stats_path,
        output_path=output_path,
        canaries_path=canaries_path,
        previous_output_path=previous_output_path,
        summary_json_path=summary_json_path,
        summary_md_path=summary_md_path,
        thresholds=thresholds,
    )
    return ValidationRunResult(summary=summary, exit_code=1 if summary.errors else 0)


# =============================================================================
# CLI INTERFACE
# =============================================================================


def _parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(
        prog="scripts.release_validator",
        description="Validate release candidate safety before publishing.",
    )
    parser.add_argument("--source-health", required=True, help="Path to source-health JSON")
    parser.add_argument("--pipeline-stats", required=True, help="Path to pipeline-stats JSON")
    parser.add_argument("--output", required=True, help="Path to current merged output")
    parser.add_argument("--canaries", required=True, help="Path to release canaries JSON")
    parser.add_argument("--previous-output", help="Optional previous release output")
    parser.add_argument("--summary-json", required=True, help="Path for validation JSON summary")
    parser.add_argument("--summary-md", required=True, help="Path for validation Markdown summary")
    parser.add_argument(
        "--minimum-output-rules",
        type=int,
        default=DEFAULT_MINIMUM_OUTPUT_RULES,
        help="Hard minimum emitted rule count",
    )
    return parser.parse_args()


def main() -> int:
    """CLI entry point."""
    args = _parse_args()
    previous_output = Path(args.previous_output) if args.previous_output else None
    thresholds = ReleaseThresholds(minimum_output_rules=args.minimum_output_rules)

    try:
        result = run_validation(
            source_health_path=Path(args.source_health),
            pipeline_stats_path=Path(args.pipeline_stats),
            output_path=Path(args.output),
            canaries_path=Path(args.canaries),
            previous_output_path=previous_output,
            summary_json_path=Path(args.summary_json),
            summary_md_path=Path(args.summary_md),
            thresholds=thresholds,
        )
        if result.exit_code:
            print(f"Release validation failed with {len(result.summary.errors)} error(s)")
        else:
            print(f"Release validation passed with {len(result.summary.warnings)} warning(s)")
        return result.exit_code
    except Exception as e:
        print(f"\nERROR: {e}", file=sys.stderr)
        import traceback

        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
